from enum import Enum

class OwgrTour(Enum):
    ALL=""
    PGATour="PGAT"
    AlpsTour="ALP"
    AsianDevelopmentTour="ADT"
    AsianTour="Asa"
    BigEasyTour="BET"
    ChallangeTour="Cha"
    ChinaTour="CHN"
    ChinaTourPgaTourSeries="CTPTC"
    EuroTour="Eur"
    EuroProTour="EPT"
    JapanTour="Jpn"
    KoreaTour="Kor"
    CanadaTour="Can"
    MajorChampionships="Maj"
    MenaGolfTour="MGT"
    NordicGolfLeague="NGL"
    OlympicGolfCompetition="OGC"
    OneAsiaTour="One"
    PgaTourLatinoAmerica="SAm"
    PgaTourAustralasia="ANZ"
    ProTourSeriesChina="PTSC"
    ProGolfTour="PGT"
    SunshineTour="Afr"
    WebTour="Web"
    WorldGolfChampionships="WGC"